"""Markdown report generator."""

from __future__ import annotations

from datetime import datetime, timezone

from .models import FindingType, ScanReport

TYPE_LABELS = {
    FindingType.SECRET: ("Secrets & Credentials", "Hardcoded secrets, API keys, passwords, tokens, and private keys."),
    FindingType.INTERNAL_URL: ("Internal URLs", "URLs pointing to internal government infrastructure."),
    FindingType.INTERNAL_HOSTNAME: ("Internal Hostnames", "Server names and internal infrastructure identifiers."),
    FindingType.SENSITIVE_ALGORITHM: ("Sensitive Algorithms", "Government-specific business logic that may require review before publication."),
}

TYPE_ORDER = [
    FindingType.SECRET,
    FindingType.INTERNAL_URL,
    FindingType.INTERNAL_HOSTNAME,
    FindingType.SENSITIVE_ALGORITHM,
]


def render_markdown(report: ScanReport) -> str:
    """Render a ScanReport as a Markdown document."""
    lines: list[str] = []

    lines.append("# OSS Sanitizer — Compliance Report")
    lines.append("")
    lines.append(f"**Repository:** `{report.repo_path}`")
    lines.append(f"**Date:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"**History scanned:** {'Yes' if report.scan_history else 'No (working tree only)'}")
    lines.append(f"**Total findings:** {len(report.findings)}")
    lines.append(f"**Total risk score:** {report.total_score:.1f}")
    lines.append("")

    # Summary table
    grouped = report.findings_by_type()
    lines.append("## Summary")
    lines.append("")
    lines.append("| Category | Count | Score |")
    lines.append("|----------|------:|------:|")

    for ftype in TYPE_ORDER:
        label, _ = TYPE_LABELS[ftype]
        items = grouped.get(ftype, [])
        score = sum(f.score for f in items)
        lines.append(f"| {label} | {len(items)} | {score:.1f} |")

    lines.append("")

    if not report.findings:
        lines.append("> **No findings.** The repository appears compliant with the Geneva Open Source Charter §2 (Confidentialité).")
        return "\n".join(lines)

    # Detailed findings by type
    lines.append("---")
    lines.append("")

    for ftype in TYPE_ORDER:
        items = grouped.get(ftype, [])
        if not items:
            continue

        label, description = TYPE_LABELS[ftype]
        lines.append(f"## {label}")
        lines.append("")
        lines.append(f"*{description}*")
        lines.append("")

        for idx, finding in enumerate(items, 1):
            lines.append(f"### {idx}. {finding.description}")
            lines.append("")
            lines.append(f"- **File:** `{finding.file_path}`")
            lines.append(f"- **Line:** {finding.line_number}")
            lines.append(f"- **Score:** {finding.score:.1f}")
            if finding.commit_sha:
                lines.append(f"- **Last seen in commit:** `{finding.commit_sha[:12]}`")
            lines.append("")
            lines.append(f"**Why:** {finding.explanation}")
            lines.append("")
            lines.append("```")
            lines.append(finding.snippet)
            lines.append("```")
            lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*Report generated by [oss-sanitizer](https://github.com/republique-et-canton-de-geneve/open-source-sanitizer) "
                  "— compliance checks based on the [Charte Open Source](https://github.com/republique-et-canton-de-geneve/strategie-open-source/blob/main/charte_open_source.md).*")

    return "\n".join(lines)
